import type { ManifestEntry } from "../manifest";
import type { ComponentCategory } from "./types";

/**
 * Lightweight component manifest — contains only the metadata needed by
 * the sidebar and components list (name, label, category, description,
 * example count). This avoids pulling in all demo components, ?raw, and
 * ?highlighted strings that the full registry files import.
 */
export const componentManifest: ManifestEntry[] = [
  {
    name: "accordion",
    label: "Accordion",
    category: "Layout",
    description: "Collapsible content sections.",
    exampleCount: 6,
    isNew: false,
  },
  {
    name: "alert",
    label: "Alert",
    category: "Feedback",
    description: "Status callout with variants.",
    exampleCount: 3,
    isNew: false,
  },
  {
    name: "alert-dialog",
    label: "Alert Dialog",
    category: "Overlay",
    description: "Modal for destructive confirmations.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "avatar",
    label: "Avatar",
    category: "Layout",
    description: "User image with fallback.",
    exampleCount: 4,
    isNew: false,
  },
  {
    name: "badge",
    label: "Badge",
    category: "Feedback",
    description: "Compact status indicator.",
    exampleCount: 8,
    isNew: false,
  },
  {
    name: "breadcrumb",
    label: "Breadcrumb",
    category: "Navigation",
    description: "Hierarchical navigation trail.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "button",
    label: "Button",
    category: "Form",
    description: "Action trigger in 8 variants.",
    exampleCount: 6,
    isNew: false,
  },
  {
    name: "button-group",
    label: "Button Group",
    category: "Form",
    description: "Joined row of related buttons.",
    exampleCount: 12,
    isNew: false,
  },
  {
    name: "card",
    label: "Card",
    category: "Layout",
    description: "Sectioned content container.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "checkbox",
    label: "Checkbox",
    category: "Form",
    description: "Binary selection control.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "collapsible",
    label: "Collapsible",
    category: "Layout",
    description: "Expandable content panel.",
    exampleCount: 4,
    isNew: true,
  },
  {
    name: "combobox",
    label: "Combobox",
    category: "Form",
    description: "Searchable option picker.",
    exampleCount: 10,
    isNew: true,
  },
  {
    name: "command",
    label: "Command",
    category: "Overlay",
    description: "Keyboard-driven command palette.",
    exampleCount: 5,
    isNew: false,
  },
  {
    name: "context-menu",
    label: "Context Menu",
    category: "Overlay",
    description: "Right-click action menu.",
    exampleCount: 10,
    isNew: false,
  },
  {
    name: "dialog",
    label: "Dialog",
    category: "Overlay",
    description: "Modal window with overlay.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "dropdown-menu",
    label: "Dropdown Menu",
    category: "Overlay",
    description: "Button-triggered action menu.",
    exampleCount: 12,
    isNew: false,
  },
  {
    name: "empty",
    label: "Empty",
    category: "Feedback",
    description: "Structured empty-state layout.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "field",
    label: "Field",
    category: "Form",
    description: "Composable form field parts.",
    exampleCount: 11,
    isNew: true,
  },
  {
    name: "glow",
    label: "Glow",
    category: "Motion",
    description: "Accent halo on interaction.",
    exampleCount: 4,
    isNew: false,
  },
  {
    name: "hover-card",
    label: "Hover Card",
    category: "Overlay",
    description: "Preview card on hover.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "input",
    label: "Input",
    category: "Form",
    description: "Text input field.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "input-group",
    label: "Input Group",
    category: "Form",
    description: "Input with attached addons.",
    exampleCount: 4,
    isNew: false,
  },
  {
    name: "label",
    label: "Label",
    category: "Form",
    description: "Accessible form label.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "magnetic",
    label: "Magnetic",
    category: "Motion",
    description: "Cursor attraction effect.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "mode-switcher",
    label: "Mode Switcher",
    category: "Feedback",
    description: "Theme toggle with radial reveal.",
    exampleCount: 1,
    isNew: true,
  },
  {
    name: "native-select",
    label: "Native Select",
    category: "Form",
    description: "Styled native select.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "pagination",
    label: "Pagination",
    category: "Navigation",
    description: "Page navigation controls.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "popover",
    label: "Popover",
    category: "Overlay",
    description: "Floating content panel.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "progress",
    label: "Progress",
    category: "Feedback",
    description: "Task completion bar.",
    exampleCount: 3,
    isNew: false,
  },
  {
    name: "pulse",
    label: "Pulse",
    category: "Motion",
    description: "Periodic attention halo.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "radio-group",
    label: "Radio Group",
    category: "Form",
    description: "Single-choice option set.",
    exampleCount: 6,
    isNew: false,
  },
  {
    name: "reveal",
    label: "Reveal",
    category: "Motion",
    description: "Scroll-triggered entrance.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "ripple",
    label: "Ripple",
    category: "Motion",
    description: "Radial expanding circle on press.",
    exampleCount: 3,
    isNew: true,
  },
  {
    name: "scroll-area",
    label: "Scroll Area",
    category: "Layout",
    description: "Custom-styled scroll region.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "scramble",
    label: "Scramble",
    category: "Motion",
    description: "Text decoding visual effect.",
    exampleCount: 2,
    isNew: true,
  },
  {
    name: "select",
    label: "Select",
    category: "Form",
    description: "Dropdown option picker.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "separator",
    label: "Separator",
    category: "Layout",
    description: "Content divider.",
    exampleCount: 4,
    isNew: false,
  },
  {
    name: "sheet",
    label: "Sheet",
    category: "Overlay",
    description: "Slide-in side panel.",
    exampleCount: 3,
    isNew: false,
  },
  {
    name: "skeleton",
    label: "Skeleton",
    category: "Feedback",
    description: "Loading placeholder.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "slider",
    label: "Slider",
    category: "Form",
    description: "Range value input.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "spinner",
    label: "Spinner",
    category: "Feedback",
    description: "Animated loading indicator.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "spotlight",
    label: "Spotlight",
    category: "Motion",
    description: "Pointer-following highlight.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "switch",
    label: "Switch",
    category: "Form",
    description: "On/off toggle control.",
    exampleCount: 6,
    isNew: false,
  },
  {
    name: "table",
    label: "Table",
    category: "Data",
    description: "Responsive data table.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "tabs",
    label: "Tabs",
    category: "Navigation",
    description: "Tabbed content panels.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "textarea",
    label: "Textarea",
    category: "Form",
    description: "Multi-line text input.",
    exampleCount: 2,
    isNew: false,
  },
  {
    name: "tilt",
    label: "Tilt",
    category: "Motion",
    description: "Perspective tilt toward the cursor.",
    exampleCount: 2,
    isNew: true,
  },
  {
    name: "toast",
    label: "Toast",
    category: "Feedback",
    description: "Transient notification.",
    exampleCount: 6,
    isNew: true,
  },
  {
    name: "toggle",
    label: "Toggle",
    category: "Form",
    description: "Pressable on/off button.",
    exampleCount: 5,
    isNew: false,
  },
  {
    name: "toggle-group",
    label: "Toggle Group",
    category: "Form",
    description: "Grouped on/off buttons.",
    exampleCount: 6,
    isNew: false,
  },
  {
    name: "tooltip",
    label: "Tooltip",
    category: "Overlay",
    description: "Hover-triggered label.",
    exampleCount: 1,
    isNew: false,
  },
  {
    name: "trace",
    label: "Trace",
    category: "Motion",
    description: "Accent beam along element's border.",
    exampleCount: 2,
    isNew: true,
  },
];

export const componentCategories: ComponentCategory[] = [
  "Form",
  "Layout",
  "Overlay",
  "Feedback",
  "Navigation",
  "Data",
  "Motion",
];
